name: Main

on: [push, pull_request]

jobs:
  lint:
    name: Lint with xojs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Lint
      run: |
        npm install
        npm run lint
      env:
        CI: true
        NODE_ENV: development
  build:
    name: Build and test binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Build
      run: |
        npm install
        npm install --dev
        npm run build-ci
        npm test
      env:
        CI: true
        NODE_ENV: production
